pipeline:
  dco:
    group: meta
    image: algernon/drone-plugin-dco

  signature-check:
    group: meta
    image: algernon/drone-plugin-signature-check
    when:
      event: tag

  bootstrap:
    image: algernon/drone-language:emacs
    bootstrap: true

  byte-compile:
    group: testing
    image: algernon/drone-language:emacs
    byte_compile:
      - brutalist-theme-builder.el
      - brutalist-theme.el
      - brutalist-dark-theme.el

  lint:
    group: testing
    image: algernon/drone-language:emacs
    lint:
      - brutalist-theme-builder.el
      - brutalist-theme.el
      - brutalist-dark-theme.el

  checkdoc:
    group: testing
    image: algernon/drone-language:emacs
    checkdoc:
      - brutalist-theme-builder.el
      - brutalist-theme.el
      - brutalist-dark-theme.el
